# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'


source 'https://github.com/CocoaPods/Specs.git'
target 'geolocrec' do
  pod 'GoogleMaps'
  pod 'GooglePlaces'
end



 #target 'geolocrec' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for geolocrec

  target 'geolocrecTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'geolocrecUITests' do
    inherit! :search_paths
    # Pods for testing
  end


