# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='geolocation',
            fields=[
                ('fenceId', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius', models.FloatField()),
            ],
        ),
    ]
