# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requesthandler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('couponId', models.PositiveIntegerField()),
                ('fenceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='requesthandler.Geolocation')),
            ],
        ),
        migrations.AddField(
            model_name='geolocation',
            name='locationAddr',
            field=models.TextField(default='NULL'),
        ),
        migrations.AddField(
            model_name='geolocation',
            name='locationName',
            field=models.CharField(default='NULL', max_length=50),
        ),
    ]
