# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requesthandler', '0002_auto_20181128_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='couponText',
            field=models.TextField(default='NULL'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='fenceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='requesthandler.Geolocation'),
        ),
    ]
