# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requesthandler', '0003_auto_20181128_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('coupon', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('couponText', models.TextField(default='NULL')),
            ],
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='fenceId',
        ),
        migrations.RenameField(
            model_name='geolocation',
            old_name='fenceId',
            new_name='fence',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.AddField(
            model_name='coupons',
            name='fence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requesthandler.Geolocation'),
        ),
    ]
