# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requesthandler', '0005_auto_20181128_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupons',
            old_name='couponId',
            new_name='coupon_id',
        ),
        migrations.RenameField(
            model_name='coupons',
            old_name='couponText',
            new_name='coupon_text',
        ),
        migrations.RenameField(
            model_name='coupons',
            old_name='fenceId',
            new_name='fence_id',
        ),
        migrations.RenameField(
            model_name='geolocation',
            old_name='fenceId',
            new_name='fence_id',
        ),
        migrations.RenameField(
            model_name='geolocation',
            old_name='locationAddr',
            new_name='location_addr',
        ),
        migrations.RenameField(
            model_name='geolocation',
            old_name='locationName',
            new_name='location_name',
        ),
        migrations.AlterField(
            model_name='coupons',
            name='fence_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requesthandler.Geolocation'),
        ),
    ]
