# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requesthandler', '0006_auto_20181128_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='fence_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requesthandler.Geolocation'),
        ),
    ]
